[01-Mar-2022 11:31:28 Asia/Tehran] Uncaught exception: 'Bolt\error\MessageException' with message 'Invalid input '': expected "*", "DISTINCT" or an expression (line 1, column 147 (offset: 146))
"MATCH (p:Post { uuid:"93bb372a-4bd2-4cdf-8c8e-72a02aef2149" })-[r]->(b), (u:User { uuid:"2f6c7cae-5c13-4292-903f-443b2da20900" })-[r]->(p) RETURN"
                                                                                                                                                   ^ (Neo.ClientError.Statement.SyntaxError)'
Stack trace: #0 I:\Projects\medium\core\QueryBuilder.php(199): Bolt\protocol\V3->run('MATCH (p:Post {...')
#1 I:\Projects\medium\app\controllers\PostController.php(164): Core\QueryBuilder->return(Array)
#2 [internal function]: App\Controllers\PostController->delete(Object(Core\Request))
#3 I:\Projects\medium\core\Controller.php(30): call_user_func_array(Array, Array)
#4 [internal function]: Core\Controller->__call('delete', Array, controller: 'App\\Controllers...', action: 'delete', params: Array)
#5 I:\Projects\medium\core\Router.php(149): call_user_func_array(Array, Array)
#6 I:\Projects\medium\core\Bootstrap.php(43): Core\Router->dispatch('post/93bb372a-4...')
#7 I:\Projects\medium\public\index.php(17): Core\Bootstrap->run()
#8 {main}
Thrown in 'I:\Projects\medium\vendor\stefanak-michal\bolt\src\protocol\V3.php' on line 82
[01-Mar-2022 11:31:29 Asia/Tehran] Uncaught exception: 'Bolt\error\MessageException' with message 'Invalid input '': expected "*", "DISTINCT" or an expression (line 1, column 147 (offset: 146))
"MATCH (p:Post { uuid:"93bb372a-4bd2-4cdf-8c8e-72a02aef2149" })-[r]->(b), (u:User { uuid:"2f6c7cae-5c13-4292-903f-443b2da20900" })-[r]->(p) RETURN"
                                                                                                                                                   ^ (Neo.ClientError.Statement.SyntaxError)'
Stack trace: #0 I:\Projects\medium\core\QueryBuilder.php(199): Bolt\protocol\V3->run('MATCH (p:Post {...')
#1 I:\Projects\medium\app\controllers\PostController.php(164): Core\QueryBuilder->return(Array)
#2 [internal function]: App\Controllers\PostController->delete(Object(Core\Request))
#3 I:\Projects\medium\core\Controller.php(30): call_user_func_array(Array, Array)
#4 [internal function]: Core\Controller->__call('delete', Array, controller: 'App\\Controllers...', action: 'delete', params: Array)
#5 I:\Projects\medium\core\Router.php(149): call_user_func_array(Array, Array)
#6 I:\Projects\medium\core\Bootstrap.php(43): Core\Router->dispatch('post/93bb372a-4...')
#7 I:\Projects\medium\public\index.php(17): Core\Bootstrap->run()
#8 {main}
Thrown in 'I:\Projects\medium\vendor\stefanak-michal\bolt\src\protocol\V3.php' on line 82
[01-Mar-2022 11:31:58 Asia/Tehran] Uncaught exception: 'Bolt\error\MessageException' with message 'Cannot use the same relationship variable 'r' for multiple patterns (line 1, column 65 (offset: 64))
"MATCH (p:Post { uuid:"93bb372a-4bd2-4cdf-8c8e-72a02aef2149" })-[r]->(b), (u:User { uuid:"2f6c7cae-5c13-4292-903f-443b2da20900" })-[r]->(p) RETURN u, p"
                                                                 ^ (Neo.ClientError.Statement.SyntaxError)'
Stack trace: #0 I:\Projects\medium\core\QueryBuilder.php(199): Bolt\protocol\V3->run('MATCH (p:Post {...')
#1 I:\Projects\medium\app\controllers\PostController.php(164): Core\QueryBuilder->return(Array)
#2 [internal function]: App\Controllers\PostController->delete(Object(Core\Request))
#3 I:\Projects\medium\core\Controller.php(30): call_user_func_array(Array, Array)
#4 [internal function]: Core\Controller->__call('delete', Array, controller: 'App\\Controllers...', action: 'delete', params: Array)
#5 I:\Projects\medium\core\Router.php(149): call_user_func_array(Array, Array)
#6 I:\Projects\medium\core\Bootstrap.php(43): Core\Router->dispatch('post/93bb372a-4...')
#7 I:\Projects\medium\public\index.php(17): Core\Bootstrap->run()
#8 {main}
Thrown in 'I:\Projects\medium\vendor\stefanak-michal\bolt\src\protocol\V3.php' on line 82
[01-Mar-2022 12:08:28 Asia/Tehran] Uncaught exception: 'Bolt\error\MessageException' with message 'Message 'PULL Map{n -> Long(-1)}' cannot be handled by a session in the READY state. (Neo.ClientError.Request.Invalid)'
Stack trace: #0 I:\Projects\medium\core\QueryBuilder.php(208): Bolt\protocol\V4->pull()
#1 I:\Projects\medium\app\controllers\PostController.php(164): Core\QueryBuilder->return(Array)
#2 [internal function]: App\Controllers\PostController->delete(Object(Core\Request))
#3 I:\Projects\medium\core\Controller.php(30): call_user_func_array(Array, Array)
#4 [internal function]: Core\Controller->__call('delete', Array, controller: 'App\\Controllers...', action: 'delete', params: Array)
#5 I:\Projects\medium\core\Router.php(149): call_user_func_array(Array, Array)
#6 I:\Projects\medium\core\Bootstrap.php(43): Core\Router->dispatch('post/93bb372a-4...')
#7 I:\Projects\medium\public\index.php(17): Core\Bootstrap->run()
#8 {main}
Thrown in 'I:\Projects\medium\vendor\stefanak-michal\bolt\src\protocol\V4.php' on line 55
